### ISSUE TITLE
Page is empty on fresh installation

### ISSUE THREAD

**Issue by cyterdan** [regseb/gout#3]
followed instructions to install and start but the page at localhost:3000 is empty

**Comment by cyterdan** [comment]
requires chrome 49 > 

please update the readme

**Comment by regseb** [comment]
Après avoir analysé toutes les données envoyées :wink:, je pense aussi que le problème vient du navigateur. Le _README_ a été mis à jour pour indiquer les navigateurs compatibles (Firefox 48+ et Chrome 52+). 82206c1d677e4460d7e7ebc7c9bb622a27e8aa49
